apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: "1GB"
              cpu: "100m"
            limits:
              memory: "2GB"
              cpu: "500m"
          securityContext:
            runAsUser: 101  
            runAsNonRoot: true
            readOnlyRootFilesystem: true
  volumeClaimTemplates:
    - metadata:
        name: nginx-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
